### ISSUE TITLE
URL on Bans needs change on release.

### ISSUE THREAD

**Issue by MrDraqon** [kangarko/docs#4]
Just a reminder for when Bans is released the URL on the home page when hovering over the name in the box are currently linked to protect, it needs to be changed once the plugin has been uploaded to BBB

![image](https://github.com/user-attachments/assets/adf4646b-3c8e-4916-9fd4-ba850081b357)

**Comment by kangarko** [comment]
Yes I noticed it, I will change that before the release thank you!
