### ISSUE TITLE
Bans plugin adjustments

### ISSUE THREAD

**Issue by kangarko** [kangarko/docs#5]
- [x] Rename Bans-Plugin to Bans (use Search Everywhere)
- [x] Change link to mineacademy.org/bans on homepage
- [x] Change home page text to: "A modern punishment plugin with Velocity, BungeeCord and Discord support and a reporting system."
- [x] Change white image at Discord page to updated DiscordSVR documentation
- [x] Add link to github.com/kangarko/bans/issues to the main page of Bans
- [x] Remove This plugin is on github from Bans at home

@BouncingSquirrel

**Comment by BouncingSquirrel** [comment]
- [ ] Get *Bans* documentation more to *MineBot*'s documentation format (cleanup)
- [ ] Change DiscordSVR config image (Bans > Discord) to SVR's documentation link
- [ ] Install Mkdocs "Page Authors" plugin

**Comment by kangarko** [comment]
Tag me when done please
