### ISSUE TITLE
Rework credits

### ISSUE THREAD

**Issue by BouncingSquirrel** [kangarko/docs#7]
- [ ] Change credits to only About Page
- [x] Remove `Made with Material for MkDocs`

**Comment by BouncingSquirrel** [comment]
@kangarko Do you want The credits to only be "@MineAcademy"?

**Comment by BouncingSquirrel** [comment]
We could add this badge to the README.md when removing the notice from the footer to provide some credits: [badge](https://squidfunk.github.io/mkdocs-material/blog/2023/11/30/adding-a-badge-to-your-project/)

**Comment by kangarko** [comment]
I'll take care of this before launch, thanks

**Comment by BouncingSquirrel** [comment]
@kangarko And maybe consider removing the second `!`...haha
